THEOS_DEVICE_IP=192.168.1.106
SDKVERSION=4.3

include theos/makefiles/common.mk

TWEAK_NAME = FolderLockFREE
FolderLockFREE_FILES = Tweak.xm
FolderLockFREE_FRAMEWORKS = UIKit
SUBPROJECTS = folderlockfreesettings

include $(THEOS_MAKE_PATH)/tweak.mk
include $(THEOS_MAKE_PATH)/aggregate.mk
