THEOS_DEVICE_IP=192.168.1.106
SDKVERSION = 4.3

include theos/makefiles/common.mk

TWEAK_NAME = EasyRespring
EasyRespring_FILES = Tweak.xm
EasyRespring_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/tweak.mk
