SDKVERSION=4.3
THEOS_DEVICE_IP=192.168.1.106

include theos/makefiles/common.mk

TWEAK_NAME = RemovedSound
RemovedSound_FILES = Tweak.xm
RemovedSound_FRAMEWORKS = UIKit AVFoundation
include $(THEOS_MAKE_PATH)/tweak.mk
